# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('big_brother', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='littles', to='fraternity_tree.Brother')),
            ],
            options={
                'verbose_name_plural': 'Brothers',
                'verbose_name': 'Brother',
            },
        ),
        migrations.CreateModel(
            name='PledgeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('date_initiated', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Pledge Classes',
                'verbose_name': 'Pledge Class',
            },
        ),
        migrations.AddField(
            model_name='brother',
            name='pledge_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fraternity_tree.PledgeClass'),
        ),
    ]
