# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brother',
            old_name='big_brother',
            new_name='parent',
        ),
    ]
