# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0002_auto_20170225_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgeclass',
            name='date_initiated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
