# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0003_auto_20170225_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('university', models.CharField(max_length=256)),
                ('founders_day', models.DateField()),
                ('street_address', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.AlterModelOptions(
            name='brother',
            options={'ordering': ['pledge_class', 'last_name', 'first_name'], 'verbose_name': 'Brother', 'verbose_name_plural': 'Brothers'},
        ),
        migrations.AlterModelOptions(
            name='pledgeclass',
            options={'ordering': ['date_initiated', 'name'], 'verbose_name': 'Pledge Class', 'verbose_name_plural': 'Pledge Classes'},
        ),
        migrations.AddField(
            model_name='brother',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brother',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brother',
            name='membership_status',
            field=models.CharField(choices=[('Alumnus', 'Alumnus'), ('Expelled - Automatic', 'Expelled - Automatic'), ('Expelled - Chapter', 'Expelled - Chapter'), ('Expelled - National/COS', 'Expelled - National/COS'), ('Honarary', 'Honarary'), ('Good Standing', 'Good Standing'), ('Suspended - Automatic', 'Suspended - Automatic'), ('Suspended - Chapter', 'Suspended - Chapter'), ('Suspended - Unknown', 'Suspended - Unknown')], default='Alumnus', max_length=32),
        ),
        migrations.AddField(
            model_name='brother',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fraternity_tree.Chapter'),
            preserve_default=False,
        ),
    ]
