# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0004_auto_20170226_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brother',
            name='membership_status',
            field=models.CharField(choices=[('Alumnus', 'Alumnus'), ('Expelled - Automatic', 'Expelled - Automatic'), ('Expelled - Chapter', 'Expelled - Chapter'), ('Expelled - National/COS', 'Expelled - National/COS'), ('Honarary', 'Honarary'), ('Good Standing', 'Good Standing'), ('Suspended - Automatic', 'Suspended - Automatic'), ('Suspended - Chapter', 'Suspended - Chapter'), ('Suspended - Unknown', 'Suspended - Unknown'), ('Probationary', 'Probationary')], default='Alumnus', max_length=32),
        ),
    ]
