# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-15 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0005_auto_20170226_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledgeclass',
            options={'ordering': ['date_initiated'], 'verbose_name': 'Pledge Class', 'verbose_name_plural': 'Pledge Classes'},
        ),
    ]
