# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-17 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0006_auto_20171015_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brother',
            options={'ordering': ['pledge_class__date_initiated', 'last_name', 'first_name'], 'verbose_name': 'Brother', 'verbose_name_plural': 'Brothers'},
        ),
    ]
