# Generated by Django 3.1.2 on 2020-12-12 17:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fraternity_tree', '0009_auto_20171017_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brother',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brother',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='brother',
            name='email',
        ),
        migrations.RemoveField(
            model_name='brother',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='brother',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fraternity_tree.chapter'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='brother',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='brother',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='littles', to='fraternity_tree.brother'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='pledge_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fraternity_tree.pledgeclass'),
        ),
        migrations.AlterField(
            model_name='brother',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
